spring:
    datasource:
        db:
        url: jdbc:h2:mem:test_db_a;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL;
        driver-class-name: org.h2.Driver
        username: sa
        password: sa
    flyway:
        enabled: true
        locations:
        - classpath:/sql
